# Generated by Django 5.2.1 on 2025-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Name')),
                ('Surname', models.TextField(verbose_name='Surname')),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('Qualification', models.CharField(max_length=50, verbose_name='Qualification')),
            ],
        ),
    ]
